### PR TITLE
Fix build with tokio 0.2

### PR DESCRIPTION
**Pull request by r-arias**
I got this to run with minor changes.

Hope this helps! 
Cheers
r

### CODE REVIEW

**Comment by r-arias** [comment]
@sticnarf I am having a hard time setting up the test env on my machine to reproduce the CI failures. Could you let me know if these are actually my fault? Then I could try to put more effort into finding the problem :)

**Comment by sticnarf** [comment]
I'm also confused about it. The test works quite well on my computer.

**Comment by sticnarf** [comment]
Once I thought there was something wrong with the CI environment. So I try GitHub actions and nothing changes.

Finally I find the problem is that necessary tokio features are not enabled. I enable `full` features of tokio in https://github.com/sticnarf/tokio-socks/pull/13 and it passes the tests.

You can try how to minimize the features.

**Comment by r-arias** [comment]
yep, I can confirm that my branch works with `full`, I'll try and see which feature messes things up when it goes missing.

**Comment by r-arias** [comment]
Ok, I got it down to just my original features + `"rt-threaded"` in dev-dependencies.

**Comment by r-arias** [comment]
It still fails on travis (in beta, with "Connection refused") but I suspect that's an issue with the test setup.

My branch does not contain the deactivation of parallel tests and of `connect_no_auth`.

**Comment by sticnarf** [comment]
The deactivation of parallel tests and of connect_no_auth is only for my debug :)

I will replace travis with github actions so I will ignore the travis failure. If it fails frequently on GitHub actions, I will try to make it more stable then.

**Comment by r-arias** [comment]
Sure!
Will you create a release from this?

**Pull request merged**
